    var ContryNames =["Afghanistan", "Åland Islands", "Albania", "Algeria", "American Samoa", "Andorra", "Angola", "Anguilla", "Antarctica", "Argentina", "Belgium", "Brazil", "Brunei Darussalam", "Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Canada", "Chile", "China", "Colombia", "Costa Rica", "Czech Republic", "Denmark", "Dominica", "El Salvador", "Falkland Islands (Malvinas)", "Faroe Islands", "Fiji", "Finland", "France", "French Guiana", "French Polynesia", "French Southern Territories", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece", "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala", "Guernsey", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Heard Island and Mcdonald Islands", "Holy See (Vatican City State)", "Honduras", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", "Iran, Islamic Republic Of", "Iraq", "Ireland", "Isle of Man", "Israel", "Italy", "Jamaica", "Japan", "Jersey", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Democratic People's Republic of Korea", "Korea, Republic of", "Kosovo", "Kuwait", "Kyrgyzstan", "Lao People's Democratic Republic", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libyan Arab Jamahiriya", "Liechtenstein", "Lithuania", "Luxembourg", "Macao", "Macedonia, The Former Yugoslav Republic of", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Martinique", "Mauritania", "Mauritius", "Mayotte", "Mexico", "Micronesia, Federated States of", "Moldova, Republic of", "Monaco", "Mongolia", "Montenegro", "Montserrat", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "Netherlands Antilles", "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Niue", "Norfolk Island", "Northern Mariana Islands", "Norway", "Oman", "Pakistan", "Palau", "Palestinian Territory, Occupied", "Panama", "Papua New Guinea", "Paraguay","Peru","Philippines",",Pitcairn",",Poland",",Portugal",",Puerto Rico",",Qatar",",Russian Federation",",Singapore", ",Solomon Islands",",Somalia",",South Africa",",South Georgia and the South Sandwich Islands",",Spain",",Sri Lanka",",Sudan",",Suriname",",Svalbard and Jan Mayen",",Swaziland",",Switzerland",",Taiwan",",Thailand",",Tonga",",Tunisia",",Turkey",",Tuvalu",",United Arab Emirates",",United Kingdom",",United States",",Viet Nam",",Wallis and Futuna",",Yemen",",Zimbabwe"]
    var id =["AF","AX","AL","DZ","AS","AD","AO","AI","AQ","AR","BE","BR","BN","BF","BI","KH","CM","CA" ,"CL","CN","CO","CR","CZ","DK","DM","SV","FK","FO","FJ","FI","FR","GF","PF","TF","GA","GM","GE","DE","GH","GI","GR","GL","GD","GP","GU","GT","GG","GN","GW","GY","HT","HM","VA","HN","HK","HU","IS","IN","ID","IR","IQ","IE","IM","IL","IT","JM" ,"JP","JE","JO","KZ","KE","KI","KP","KR","XK","KW","KG" ,"LA","LV","LB","LS","LR","LY","LI","LT","LU","MO","MK","MG","MW","MY","MV","ML","MT","MH","MQ","MR","MU","YT","MX","FM","MD" ,"MC","MN","ME","MS","MA" ,"MZ","MM","NA","NR","NP","NL","AN","NC","NZ" ,"NI","NE","NG","NU","NF","MP","NO" ,"OM" ,"PK" ,"PW" ,"PS","PA","PG","PY","PE","PH","PN","PL","PT","PR","QA" ,"RU","SG" ,"SB" ,"SO" ,"ZA","GS","ES","LK","SD","SR","SJ","SZ","CH","TW","TH","TO" ,"TN","TR","TV","AE" ,"GB","US","VN","WF","YE","ZW"];
    
//Script Para Adicionar os elementos no HTML 
 var totalContryes= ContryNames.length
 for (var i = 0; i < totalContryes; i++) {
    let datadiv = document.createElement('div')
    document.getElementById('infos').innerHTML +='<div class="informacoesPaises" data-id="'+id[i]+'">'+ContryNames[i]+"</div>"
    console.log(ContryNames[i]+"/"+id[i])
    }